# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98c835e5ff5dd045abb1b2d0f98eb111a624707198e7f6d068c23fd46a647ceba911e03484afb7a4da86a77bff646ce88d61136cac6135a471b0a9f392301750

test:
  secret_key_base: 856afb6ccaad98159d4ba589cdc9bd0680fc79dfdb0dc58de5ee74210a73f22d1fe7abe79ef2618d9700894094a8f1406c1cec535ae6941d1b98eb31335b87e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
